use swiggy;
select * from restaurants; 

-- 1. list of top 5 cuisines as per the revenue generated by top 5 restaurants of every cuisine
select cuisine, sum(rating_count*cost) as 'revenue'
from (select *, cost*rating_count,
row_number() over(partition by cuisine order by cost*rating_count desc) as 'rank'
from restaurants) t where t.rank < 6
group by cuisine
order by revenue desc;

-- 2. What is the of the total revenue is generated by top 1% restaurants
select sum(cost*rating_count) as 'revenue' from
(select *, cost*rating_count,
row_number() over(order by cost*rating_count desc) as 'rank'
from restaurants)
t where t.rank <= ((select count(*) from restaurants)/100);

-- 1% of revenue  - 461514000
-- total number of revenue - 2636886590

-- 3. Check the same for top 20% restaurants
select sum(cost*rating_count) as 'revenue' from
(select *, cost*rating_count,
row_number() over(order by cost*rating_count desc) as 'rank'
from restaurants)
t where t.rank <= ((select count(*) from restaurants)*0.2);

-- 4. What % of revenue is generated by top 20% of restaurants with respect to total revenue?
WITH 
q1 AS (
SELECT SUM(cost * rating_count) AS 'top_revenue'
FROM (SELECT *,cost * rating_count,
ROW_NUMBER() OVER(ORDER BY cost * rating_count DESC) AS 'rank'
FROM restaurants) t WHERE t.rank <= 12280),
q2 AS (SELECT SUM(cost * rating_count) AS 'total_revenue'
FROM restaurants)
SELECT (top_revenue / total_revenue) * 100 AS 'revenue_percentage'
FROM q1, q2;

